name: Publish to GitHub Actions

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create folder and copy files
        run: |
          name=$(basename ${{ github.ref }})
          echo $name
          mkdir $name
          cp -r ru $name
          cp -r en $name
          cp -r index.html $name
          mkdir site
          cp -r $name site
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-ghpages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          keep_files: true
    
